[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "vp_template"
resolver = "2"
version = "0.2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anoma_vm_env = {path = "../../vm_env"}
borsh = "0.9.0"
wee_alloc = "0.4.5"

[dev-dependencies]
anoma_tests = {path = "../../tests"}

[patch.crates-io]
tendermint              = { git = "https://github.com/heliaxdev/tendermint-rs", branch = "yuji/rebase_v0.23.0" }
tendermint-proto        = { git = "https://github.com/heliaxdev/tendermint-rs", branch = "yuji/rebase_v0.23.0" }

[profile.release]
# smaller and faster wasm (https://rustwasm.github.io/book/reference/code-size.html#compiling-with-link-time-optimizations-lto)
lto = true
# simply terminate on panics, no unwinding
panic = "abort"
# tell llvm to optimize for size (https://rustwasm.github.io/book/reference/code-size.html#tell-llvm-to-optimize-for-size-instead-of-speed)
opt-level = 'z'
