[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "anoma_vm_env"
resolver = "2"
version = "0.2.0"

[dependencies]
anoma = {path = "../shared"}
anoma_vm_macro = {path = "../vm_macro"}
borsh = "0.9.0"
