[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "anoma"
resolver = "2"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
# NOTE "dev" features that shouldn't be used in live networks are enabled by default for now
dev = []
ferveo-tpke = [
  "tpke",
  "ark-bls12-381",
  "ark-ec",
  "ark-serialize",
  "rand_core",
  "rand_new",
]
ibc-vp = [
  "ibc",
  "ibc-proto",
]
# for integration tests and test utilies
testing = [
  "proptest",
  "rand",
  "rand_core",
  "dev",
]
wasm-runtime = [
  "loupe",
  "parity-wasm",
  "pwasm-utils",
  "wasmer-compiler-singlepass",
  "wasmer-compiler-cranelift",
  "wasmer-engine-universal",
  "wasmer-vm",
  "wasmer",
]

[dependencies]
anoma_proof_of_stake = {path = "../proof_of_stake"}
ark-bls12-381 = {version = "0.3", optional = true}
ark-ec = {version = "0.3", optional = true}
ark-serialize = {version = "0.3", optional = true}
bech32 = "0.8.0"
borsh = "0.9.0"
chrono = "0.4.19"
ed25519-dalek = {version = "1.0.1", default-features = false, features = ["rand", "u64_backend", "serde"]}
hex = "0.4.3"
tpke = {package = "group-threshold-cryptography", optional = true, git = "https://github.com/anoma/ferveo", branch = "bat/workspace-cleanup"}
# TODO temp fork for https://github.com/informalsystems/ibc-rs/issues/1161
# Also, using the same version of tendermint-rs as we do here.
ibc = {git = "https://github.com/heliaxdev/ibc-rs", branch = "yuji/rebase_v0.23.0", features = ["mocks", "borsh"], optional = true}
ibc-proto = {git = "https://github.com/heliaxdev/ibc-rs", branch = "yuji/rebase_v0.23.0", optional = true}
itertools = "0.10.0"
loupe = {version = "0.1.3", optional = true}
parity-wasm = {version = "0.42.2", optional = true}
proptest = {version = "1.0.0", optional = true}
prost = "0.9.0"
prost-types = "0.9.0"
pwasm-utils = {version = "0.18.0", optional = true}
# TODO the older versions of rand and rand_core are currently required to avoid mismatching version issue (https://github.com/dalek-cryptography/ed25519-dalek/pull/159)
rand = {version = "=0.7", optional = true}
# TODO proptest rexports the RngCore trait but the re-implementations only work for version `0.8`. *sigh*
rand_core = {version = "0.5", optional = true}
rand_new = {package = "rand", version = "0.8", optional = true}
rust_decimal = "1.14.3"
serde = {version = "1.0.125", features = ["derive"]}
sha2 = "0.9.3"
# We switch off "blake2b" because it cannot be compiled to wasm
sparse-merkle-tree = {git = "https://github.com/heliaxdev/sparse-merkle-tree", branch = "yuji/prost-0.9", features = ["borsh"]}
# temporarily using fork work-around for https://github.com/informalsystems/tendermint-rs/issues/971
tendermint = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "yuji/rebase_v0.23.0"}
thiserror = "1.0.30"
tracing = "0.1.29"
wasmer = {version = "2.0.0", optional = true}
wasmer-compiler-cranelift = {version = "2.0.0", optional = true}
wasmer-compiler-singlepass = {version = "2.0.0", optional = true}
wasmer-engine-universal = {version = "2.0.0", optional = true}
wasmer-vm = {version = "2.0.0", optional = true}
wasmparser = "0.79.0"

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = "0.7.2"
proptest = "1.0.0"
serde_json = "1.0.62"
test-env-log = {version = "0.2.7", default-features = false, features = ["trace"]}
tracing-subscriber = {version = "0.2.25", default-features = false, features = ["env-filter", "fmt"]}

[build-dependencies]
tonic-build = "0.6.0"
